package resource

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

type Config struct {
	CloudflareAccountID string `yaml:"cloudflare_account_id"`
	CloudflareAPIKey    string `yaml:"cloudflare_api_key"`
}

// ConfigPathOverride is set by the --config flag and takes precedence over
// CASKCONFIG and the default ~/.cask.yaml location.
var ConfigPathOverride string

// apiBaseURL is the base URL for Cloudflare's API. Exposed as a package
// variable so tests can redirect requests at an httptest.Server.
var apiBaseURL = "https://api.cloudflare.com/client/v4"

func configPath() (string, error) {
	if ConfigPathOverride != "" {
		return ConfigPathOverride, nil
	}
	if env := os.Getenv("CASKCONFIG"); env != "" {
		if !filepath.IsAbs(env) {
			return "", fmt.Errorf("CASKCONFIG must be an absolute path: %s", env)
		}
		return env, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to resolve home directory: %w", err)
	}
	return filepath.Join(home, ".cask.yaml"), nil
}

func loadConfig() (Config, error) {
	var cfg Config
	path, err := configPath()
	if err != nil {
		return cfg, err
	}
	yamlFile, err := os.ReadFile(path)
	if err != nil {
		return cfg, fmt.Errorf("failed to read config file %s: %w", path, err)
	}
	if err := yaml.Unmarshal(yamlFile, &cfg); err != nil {
		return cfg, fmt.Errorf("failed to unmarshal %s: %w", path, err)
	}
	if cfg.CloudflareAccountID == "" || cfg.CloudflareAPIKey == "" {
		return cfg, fmt.Errorf("%s must set cloudflare_account_id and cloudflare_api_key", path)
	}
	return cfg, nil
}

type Mode int

const (
	ModeShell Mode = iota
	ModeMiscellaneous
	ModeGit
)

type AutoGenerated struct {
	Result struct {
		Response string `json:"response,omitempty"`
		Usage    struct {
			PromptTokens        int `json:"prompt_tokens,omitempty"`
			CompletionTokens    int `json:"completion_tokens,omitempty"`
			TotalTokens         int `json:"total_tokens,omitempty"`
			PromptTokensDetails struct {
				CachedTokens int `json:"cached_tokens,omitempty"`
			} `json:"prompt_tokens_details,omitempty"`
		} `json:"usage,omitempty"`
	} `json:"result,omitempty"`
	Success  bool  `json:"success,omitempty"`
	Errors   []any `json:"errors,omitempty"`
	Messages []any `json:"messages,omitempty"`
}

func wrapPrompt(mode Mode, input string) string {
	switch mode {
	case ModeGit:
		return "Please suggest git commands to achieve the following goal: " + input + " and keep it short and concise, no more than 20 words and absolutely no markdown. Do not summarize my question, just suggest the commands, numbered. No more that three commands."
	case ModeMiscellaneous:
		return "Answer this technical question clearly and concisely: " + input + " and keep it short and concise, no more than 60 words and absolutely no markdown. Do not summarize my question, just answer the question."
	default:
		return "Please suggest shell commands to achieve the following goal: " + input + " and keep it short and concise, no more than 20 words and absolutely no markdown. Do not summarize my question, just suggest the commands, numbered. No more that three commands."
	}
}

// parseResponse splits a model response into individual items. The shell and
// git templates ask for a numbered list, so a leading "N. " prefix is stripped
// from each line. Blank lines are dropped.
func parseResponse(s string) []string {
	var items []string
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		// Strip a leading "N. " numbered-list prefix when present.
		if i := strings.Index(line, ". "); i > 0 {
			if _, err := strconv.Atoi(line[:i]); err == nil {
				line = line[i+2:]
			}
		}
		items = append(items, line)
	}
	return items
}

// ApiRequest sends the prompt to the model and returns the response parsed
// into a slice of items. For shell and git modes the model returns a numbered
// list (never more than three items), so callers can select one by index.
func ApiRequest(mode Mode, args []string) ([]string, error) {
	inputPrompt := strings.TrimSpace(strings.Join(args, " "))
	if inputPrompt == "" {
		return nil, fmt.Errorf("prompt is required")
	}

	cfg, err := loadConfig()
	if err != nil {
		return nil, err
	}

	prompt := wrapPrompt(mode, inputPrompt)

	payload, err := json.Marshal(map[string]string{"prompt": prompt})
	if err != nil {
		return nil, err
	}

	apiURL := apiBaseURL + "/accounts/" + cfg.CloudflareAccountID + "/ai/run/@cf/meta/llama-3.1-8b-instruct"
	req, err := http.NewRequest(http.MethodPost, apiURL, strings.NewReader(string(payload)))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+cfg.CloudflareAPIKey)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("API request failed (%s): %s", resp.Status, data)
	}

	var out AutoGenerated
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	if !out.Success {
		return nil, fmt.Errorf("API error: %v", out.Errors)
	}

	return parseResponse(out.Result.Response), nil
}
