package resource

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

type Config struct {
	CloudflareAccountID string `yaml:"cloudflare_account_id"`
	CloudflareAPIKey    string `yaml:"cloudflare_api_key"`
}

// ConfigPathOverride is set by the --config flag and takes precedence over
// CASKCONFIG and the default ~/.cask.yaml location.
var ConfigPathOverride string

// apiBaseURL is the base URL for Cloudflare's API. Exposed as a package
// variable so tests can redirect requests at an httptest.Server.
var apiBaseURL = "https://api.cloudflare.com/client/v4"

func configPath() (string, error) {
	if ConfigPathOverride != "" {
		return ConfigPathOverride, nil
	}
	if env := os.Getenv("CASKCONFIG"); env != "" {
		if !filepath.IsAbs(env) {
			return "", fmt.Errorf("CASKCONFIG must be an absolute path: %s", env)
		}
		return env, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to resolve home directory: %w", err)
	}
	return filepath.Join(home, ".cask.yaml"), nil
}

func loadConfig() (Config, error) {
	var cfg Config
	path, err := configPath()
	if err != nil {
		return cfg, err
	}
	yamlFile, err := os.ReadFile(path)
	if err != nil {
		return cfg, fmt.Errorf("failed to read config file %s: %w", path, err)
	}
	if err := yaml.Unmarshal(yamlFile, &cfg); err != nil {
		return cfg, fmt.Errorf("failed to unmarshal %s: %w", path, err)
	}
	if cfg.CloudflareAccountID == "" || cfg.CloudflareAPIKey == "" {
		return cfg, fmt.Errorf("%s must set cloudflare_account_id and cloudflare_api_key", path)
	}
	return cfg, nil
}

type Mode int

const (
	ModeShell Mode = iota
	ModeMiscellaneous
	ModeGit
)

type AutoGenerated struct {
	Result struct {
		Response string `json:"response,omitempty"`
		Usage    struct {
			PromptTokens        int `json:"prompt_tokens,omitempty"`
			CompletionTokens    int `json:"completion_tokens,omitempty"`
			TotalTokens         int `json:"total_tokens,omitempty"`
			PromptTokensDetails struct {
				CachedTokens int `json:"cached_tokens,omitempty"`
			} `json:"prompt_tokens_details,omitempty"`
		} `json:"usage,omitempty"`
	} `json:"result,omitempty"`
	Success  bool  `json:"success,omitempty"`
	Errors   []any `json:"errors,omitempty"`
	Messages []any `json:"messages,omitempty"`
}

// commandRules is the strict instruction block shared by the shell and git
// modes. Sending these as a system message (rather than gluing them onto the
// user's text) makes small instruct models obey them far more reliably.
const commandRules = "Reply with at most 3 commands. " +
	"Put each command on its own line, numbered like \"1.\", \"2.\", \"3.\". " +
	"Output only the raw commands themselves. " +
	"Do NOT use markdown, code fences, or backticks. " +
	"Do NOT add any explanation, notes, comments, alternatives, or restate the question. " +
	"Stop after the last command."

// systemPrompt returns the instruction block sent as the system message for
// each mode.
func systemPrompt(mode Mode) string {
	switch mode {
	case ModeGit:
		return "You suggest git commands to achieve the user's goal. " + commandRules
	case ModeMiscellaneous:
		return "Answer the user's technical question clearly and concisely in no more than 60 words. " +
			"Output plain text only. Do NOT use markdown, code fences, or backticks. Do NOT restate the question."
	default:
		return "You suggest shell commands to achieve the user's goal. " + commandRules
	}
}

type chatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type chatRequest struct {
	Messages    []chatMessage `json:"messages"`
	Temperature float64       `json:"temperature,omitempty"`
	MaxTokens   int           `json:"max_tokens,omitempty"`
}

// parseResponse splits a model response into individual items. The shell and
// git templates ask for a numbered list, so a leading "N. " prefix is stripped
// from each line. Blank lines are dropped. Command modes are capped at three
// items as a safety net in case the model ignores the instruction.
func parseResponse(mode Mode, s string) []string {
	var items []string
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		// Drop markdown code-fence lines like "```" or "```shell" that smaller
		// models sometimes emit despite being told not to.
		if strings.HasPrefix(line, "```") {
			continue
		}
		// Strip a leading "N. " numbered-list prefix when present.
		if i := strings.Index(line, ". "); i > 0 {
			if _, err := strconv.Atoi(line[:i]); err == nil {
				line = line[i+2:]
			}
		}
		items = append(items, line)
	}
	// Shell and git modes promise at most three suggestions; trim any extras
	// (commentary, alternatives) the model may append.
	if mode != ModeMiscellaneous && len(items) > 3 {
		items = items[:3]
	}
	return items
}

// ApiRequest sends the prompt to the model and returns the response parsed
// into a slice of items. For shell and git modes the model returns a numbered
// list (never more than three items), so callers can select one by index.
func ApiRequest(mode Mode, args []string) ([]string, error) {
	inputPrompt := strings.TrimSpace(strings.Join(args, " "))
	if inputPrompt == "" {
		return nil, fmt.Errorf("prompt is required")
	}

	cfg, err := loadConfig()
	if err != nil {
		return nil, err
	}

	payload, err := json.Marshal(chatRequest{
		Messages: []chatMessage{
			{Role: "system", Content: systemPrompt(mode)},
			{Role: "user", Content: inputPrompt},
		},
		Temperature: 0.2,
		MaxTokens:   256,
	})
	if err != nil {
		return nil, err
	}

	apiURL := apiBaseURL + "/accounts/" + cfg.CloudflareAccountID + "/ai/run/@cf/meta/llama-3.1-8b-instruct-fast"
	req, err := http.NewRequest(http.MethodPost, apiURL, strings.NewReader(string(payload)))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+cfg.CloudflareAPIKey)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("API request failed (%s): %s", resp.Status, data)
	}

	var out AutoGenerated
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	if !out.Success {
		return nil, fmt.Errorf("API error: %v", out.Errors)
	}

	return parseResponse(mode, out.Result.Response), nil
}
