package resource

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

type Config struct {
	CloudflareAccountID string `yaml:"cloudflare_account_id"`
	CloudflareAPIKey    string `yaml:"cloudflare_api_key"`
}

// ConfigPathOverride is set by the --config flag and takes precedence over
// CASKCONFIG and the default ~/.cask.yaml location.
var ConfigPathOverride string

// apiBaseURL is the base URL for Cloudflare's API. Exposed as a package
// variable so tests can redirect requests at an httptest.Server.
var apiBaseURL = "https://api.cloudflare.com/client/v4"

// output is the writer used for ApiRequest's final response. Exposed as a
// package variable so tests can capture it without touching os.Stdout.
var output io.Writer = os.Stdout

func configPath() (string, error) {
	if ConfigPathOverride != "" {
		return ConfigPathOverride, nil
	}
	if env := os.Getenv("CASKCONFIG"); env != "" {
		if !filepath.IsAbs(env) {
			return "", fmt.Errorf("CASKCONFIG must be an absolute path: %s", env)
		}
		return env, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to resolve home directory: %w", err)
	}
	return filepath.Join(home, ".cask.yaml"), nil
}

func loadConfig() (Config, error) {
	var cfg Config
	path, err := configPath()
	if err != nil {
		return cfg, err
	}
	yamlFile, err := os.ReadFile(path)
	if err != nil {
		return cfg, fmt.Errorf("failed to read config file %s: %w", path, err)
	}
	if err := yaml.Unmarshal(yamlFile, &cfg); err != nil {
		return cfg, fmt.Errorf("failed to unmarshal %s: %w", path, err)
	}
	if cfg.CloudflareAccountID == "" || cfg.CloudflareAPIKey == "" {
		return cfg, fmt.Errorf("%s must set cloudflare_account_id and cloudflare_api_key", path)
	}
	return cfg, nil
}

type Mode int

const (
	ModeShell Mode = iota
	ModeMiscellaneous
	ModeGit
)

type AutoGenerated struct {
	Result struct {
		Response string `json:"response,omitempty"`
		Usage    struct {
			PromptTokens        int `json:"prompt_tokens,omitempty"`
			CompletionTokens    int `json:"completion_tokens,omitempty"`
			TotalTokens         int `json:"total_tokens,omitempty"`
			PromptTokensDetails struct {
				CachedTokens int `json:"cached_tokens,omitempty"`
			} `json:"prompt_tokens_details,omitempty"`
		} `json:"usage,omitempty"`
	} `json:"result,omitempty"`
	Success  bool  `json:"success,omitempty"`
	Errors   []any `json:"errors,omitempty"`
	Messages []any `json:"messages,omitempty"`
}

func wrapPrompt(mode Mode, input string) string {
	switch mode {
	case ModeGit:
		return "Please suggest git commands to achieve the following goal: " + input + " and keep it short and concise, no more than 20 words and absolutely no markdown. Do not summarize my question, just suggest the commands, numbered. No more that three commands."
	case ModeMiscellaneous:
		return "Answer this technical question clearly and concisely: " + input + " and keep it short and concise, no more than 60 words and absolutely no markdown. Do not summarize my question, just answer the question."
	default:
		return "Please suggest shell commands to achieve the following goal: " + input + " and keep it short and concise, no more than 20 words and absolutely no markdown. Do not summarize my question, just suggest the commands, numbered. No more that three commands."
	}
}

func ApiRequest(mode Mode, args []string) error {
	inputPrompt := strings.TrimSpace(strings.Join(args, " "))
	if inputPrompt == "" {
		return fmt.Errorf("prompt is required")
	}

	cfg, err := loadConfig()
	if err != nil {
		return err
	}

	prompt := wrapPrompt(mode, inputPrompt)

	payload, err := json.Marshal(map[string]string{"prompt": prompt})
	if err != nil {
		return err
	}

	apiURL := apiBaseURL + "/accounts/" + cfg.CloudflareAccountID + "/ai/run/@cf/meta/llama-3.1-8b-instruct"
	req, err := http.NewRequest(http.MethodPost, apiURL, strings.NewReader(string(payload)))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+cfg.CloudflareAPIKey)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("API request failed (%s): %s", resp.Status, data)
	}

	var out AutoGenerated
	if err := json.Unmarshal(data, &out); err != nil {
		return err
	}
	if !out.Success {
		return fmt.Errorf("API error: %v", out.Errors)
	}

	fmt.Fprintln(output, out.Result.Response)
	return nil
}
